services:
  database:
    image: postgres:17-alpine
    container_name: mindflow_db_dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  database_test:
    image: postgres:17-alpine
    container_name: mindflow_db_test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_dev:
  pgdata_test:
